plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md
theme: jekyll-theme-cayman
title: Belajar Recursive
baseurl: "education-recursive"
url: ""
